[buildPlans.iosevka-custom]
family = "Iosevka Custom"
spacing = "fontconfig-mono"
serifs = "sans"
no-cv-ss = false

  [buildPlans.iosevka-custom.variants]
  inherits = "ss05"

  [buildPlans.iosevka-custom.ligations]
  inherits = "javascript"

	[buildPlans.iosevka-custom.weights.regular]
	shape = 400
	menu = 400
	css = 400

	[buildPlans.iosevka-custom.weights.bold]
	shape = 700
	menu = 700
	css = 700

	[buildPlans.iosevka-custom.widths.normal]
	shape = 576
	menu = 5
	css = "normal"

  [buildPlans.iosevka-custom.slopes]
  upright = "normal"
  italic = "italic"
