[buildPlans.iosevka-custom]
family = "Iosevka Custom"
spacing = "term"
serifs = "sans"

  [buildPlans.iosevka-custom.variants]
  inherits = "ss05"

  [buildPlans.iosevka-custom.ligations]
  inherits = "javascript"
